---
- name: Define global variables
  hosts: localhost
  gather_facts: false
  vars: 
    server: &server debian12-temp
    sql_user_pass: &sql_user_pass test12345

- name: Install packages and dependencies for NetBox
  hosts: *server
  gather_facts: false
  become: true # run as root
  tasks: 
    - name: apt install
      apt: 
        pkg: "{{ item }}"
        state: latest
        update_cache: true
      loop:
        - postgresql
        - python3-psycopg2
        - redis-server
        - python3-dev 
        - python3-venv 
        - build-essential 
        - libxml2-dev 
        - libxslt1-dev 
        - libffi-dev 
        - libpq-dev 
        - libssl-dev 
        - zlib1g-dev

- name: Configure PostgreSQL on Debian
  hosts: *server
  gather_facts: false
  become: true # run as root
  become_method: su
  become_user: postgres # change to postgres user
  vars:
    sql_user_pass: *sql_user_pass
  tasks: 
    - name: Create a new PostgreSQL database with the name 'netbox'
      community.postgresql.postgresql_db:
        name: netbox
        comment: NetBox database
      
    - name: Create a new user 'netbox' in the netbox database
      community.postgresql.postgresql_user:
        db: netbox
        name: netbox
        password: "{{ sql_user_pass }}"
        role_attr_flags: SUPERUSER
        comment: NetBox as a user

- name: Install and configure NetBox
  hosts: *server
  gather_facts: false
  become: true # run as root
  vars:
    netbox_version: 3.7.6
  tasks:
    - name: Unpack the netbox package version "{{ netbox_version }}" from local folder to '/opt'
      unarchive:
        src: "src/v{{ netbox_version }}.tar.gz" # the source is in the folder the playbook is run from
        dest: /opt

    - name: Create a relative symlink to the 'netbox' folder
      file:
        src: "/opt/netbox-{{ netbox_version }}"
        dest: /opt/netbox
        state: link

    - name: Create the 'netbox' system group
      group:
        name: netbox
        state: present
        system: true

    - name: Create the 'netbox' system user that belongs to 'netbox' group
      user:
        name: netbox
        group: netbox
        system: true
      
    - name: Give some folders 'rw' permissions to the 'netbox' user and group
      file:
        path: "{{ item }}"
        owner: netbox
        group: netbox
        state: directory
        recurse: true
        mode: 0644
      loop:
        - /opt/netbox/netbox/media
        - /opt/netbox/netbox/reports
        - /opt/netbox/netbox/scripts

    - name: Copy local 'configuration.py' to remote 'netbox' directory
      copy:
        src: src/configuration.py
        dest: /opt/netbox/netbox/netbox
        owner: netbox
        group: netbox

#    - name: Run 'upgrade.sh' script
#      command:
#        cmd: bash /opt/netbox/upgrade.sh
#      register: upgrade_out
#    - debug:
#        msg: "{{ upgrade_out.stdout_lines }}"