---
- name: Define global variables
  hosts: localhost
  gather_facts: false
  vars: 
    server: &server debian12-temp #hs_netbox 
    local_src_folder: &local_src_folder src/local # src/hs_netbox
    sql_user_pass: &sql_user_pass "{{ vault_sql_user_pass }}" # have to be specified in the vault for every `server` group/host

- name: Install packages and dependencies for NetBox
  hosts: *server
  gather_facts: false
  become: true # run as root
  tasks: 
    - name: apt install
      apt: 
        pkg: "{{ item }}"
        state: latest
        update_cache: true
      loop:
        - postgresql
        - python3-psycopg2
        - redis-server
        - python3-dev 
        - python3-venv 
        - build-essential 
        - libxml2-dev 
        - libxslt1-dev 
        - libffi-dev 
        - libpq-dev 
        - libssl-dev 
        - zlib1g-dev

- name: Configure PostgreSQL on Debian
  hosts: *server
  gather_facts: false
  become: true # run as root
  become_method: su
  become_user: postgres # change to postgres user
  vars:
    sql_user_pass: *sql_user_pass
  tasks: 
    - name: Create a new PostgreSQL database with the name 'netbox'
      community.postgresql.postgresql_db:
        name: netbox
        comment: NetBox database
      
    - name: Create a new user 'netbox' in the netbox database
      community.postgresql.postgresql_user:
        db: netbox
        name: netbox
        password: "{{ sql_user_pass }}"
        role_attr_flags: SUPERUSER
        comment: NetBox as a user

- name: Configure default apps
  hosts: *server
  gather_facts: false
  become: true # run as root
  vars:
    netbox_version: 3.7.6
    local_src_folder: *local_src_folder
  tasks:
    - name: Unpack the netbox package version "{{ netbox_version }}" from local folder to '/opt'
      unarchive:
        src: "src/v{{ netbox_version }}.tar.gz" # the source is in the folder the playbook is run from
        dest: /opt

    - name: Create a relative symlink to the 'netbox' folder
      file:
        src: "/opt/netbox-{{ netbox_version }}"
        dest: /opt/netbox
        state: link

    - name: Create the 'netbox' system group
      group:
        name: netbox
        state: present
        system: true

    - name: Create the 'netbox' system user that belongs to 'netbox' group
      user:
        name: netbox
        group: netbox
        system: true
      
    - name: Give some folders 'rw' permissions to the 'netbox' user and group
      file:
        path: "{{ item }}"
        owner: netbox
        group: netbox
        state: directory
        recurse: true
        mode: 0644
      loop:
        - /opt/netbox/netbox/media
        - /opt/netbox/netbox/reports
        - /opt/netbox/netbox/scripts

    - name: Copy local 'configuration.py' to remote 'netbox' directory
      copy:
        src: "{{ local_src_folder }}/configuration.py"
        dest: /opt/netbox/netbox/netbox
        owner: netbox
        group: netbox

    - name: Create a relative symlink to schedule NetBox housekeeping task
      file:
        src: /opt/netbox/contrib/netbox-housekeeping.sh 
        dest: /etc/cron.daily/netbox-housekeeping
        state: link

    - name: Copy gunicorn configs 
      copy:
        src: "{{ local_src_folder }}/gunicorn.py"
        dest: /opt/netbox/gunicorn.py 
        owner: netbox
        group: netbox
        mode: 0660
        backup: yes

- name: Install python apps in netbox virtual environment
  hosts: *server
  gather_facts: false
  become: true # run as root
  tasks:
    - name: Copy local requirements.txt to remote 'netbox' virtual environment
      copy:
        src: requirements.txt
        dest: /opt/netbox/requirements.txt
        owner: root
        mode: 664

    - name: Copy pip packages from localhost to the remote server
      copy:
        src: pip_packages/packages
        dest: /opt

    - name: Install apps with pip from the local directory
      pip:
        requirements: /opt/netbox/requirements.txt
        virtualenv: /opt/netbox/venv/
        extra_args: "--no-index --find-links=file:///opt/packages"

- name: Configure Django settings
  hosts: *server
  gather_facts: false
  become: true # run as root
  tasks:
#    - name: Run 'upgrade.sh' script to install NetBox
#      command:
#        cmd: bash /opt/netbox/upgrade.sh
#      register: upgrade_out
#    - debug:
#        msg: "{{ upgrade_out.stdout_lines }}"

- name: Enable and run NetBox services
  hosts: *server
  gather_facts: false
  become: true # run as root
  tasks:
    - name: Copy provided netbox service files
      copy:
        remote_src: true
        src: "/opt/netbox/contrib/{{ item }}"
        dest: "/etc/systemd/system/{{ item }}"
      loop:
        - netbox.service
        - netbox-rq.service

    - name: Enable and start netbox services
      service:
        name: "{{ item }}"
        state: started
        enabled: yes
      loop:
        - netbox
        - netbox-rq

- name: Install and configure the HTTP server
  hosts: *server
  gather_facts: false
  become: true # run as root
  vars:
    local_src_folder: *local_src_folder
  tasks:
    - name: apt install nginx
      apt: 
        pkg: nginx
        state: latest
        update_cache: true

    - name: Copy the SSL certificate
      copy:
        src: "{{ local_src_folder }}/netbox.key"
        dest:  /etc/ssl/private/netbox.key 
        owner: root
        mode: 0600

    - name: Copy the SSL key
      copy:
        src: "{{ local_src_folder }}/netbox.crt"
        dest: /etc/ssl/certs/netbox.crt
        owner: root
        mode: 0600

    - name: Copy nginx config file
      copy: 
        src: "{{ local_src_folder }}/nginx.conf" 
        dest: /etc/nginx/sites-available/netbox
        backup: yes
        owner: root
        mode: 0644

    - name: Remove default nginx configs
      file: 
        path: /etc/nginx/sites-enabled/default
        state: absent
    
    - name: Link netbox configs to nginx
      file: 
        src: /etc/nginx/sites-available/netbox 
        dest: /etc/nginx/sites-enabled/default
        state: link

    - name: Restart the nginx service
      service: 
        name: nginx
        state: restarted
        enabled: yes