---
- name: Download required pip packages
  hosts: localhost
  gather_facts: false
  vars: 
    netbox_version: 4.0.3
    python_version: 3.11 # check if you have to activate the right python shell with 'pyenv shell 3.x.x'
    venv_path: pip_packages
  
  tasks:
    - name: Remove existing virtual environment folder
      file:
        path: "{{ venv_path }}"
        state: absent

    - name: Create a virtual environment
      shell: "python{{ python_version }} -m venv pip_packages"
      args:
        executable: /usr/bin/bash
      
    - name: Download required packages
      tags: download
      shell: "source bin/activate && pip download -r ../src/requirements-{{ netbox_version }}.txt -d packages"
      args:
        executable: /usr/bin/bash
        chdir: "{{ venv_path }}"