---
- name: Download required pip packages on the localhost
  hosts: localhost
  gather_facts: false
  vars: 
    netbox_version: 4.2.2
    python_version: 3.11 # check if you have to activate the right python shell with 'pyenv shell 3.11.2' | show versions 'pyenv versions'
    inventory_dir: "{{ playbook_dir }}/.." # localhost doesn't have 'inventory_dir' global variable
    venv_path: "{{ inventory_dir }}/pip_packages" 

  tasks:
    - name: Remove existing virtual environment folder
      file:
        path: "{{ venv_path }}"
        state: absent

    - name: Create a virtual environment
      shell: "python{{ python_version }} -m venv {{ venv_path }}"
      args:
        executable: /usr/bin/bash
      
    - name: Download required packages
      shell: "source bin/activate && pip download -r {{ inventory_dir }}/src/requirements-{{ netbox_version }}.txt -d packages"
      args:
        executable: /usr/bin/bash
        chdir: "{{ venv_path }}"

    - name: Download NetBox plugins
      tags: plugins
      shell: "source bin/activate && pip download {{ item }} -d plugins"
      args:
        executable: /usr/bin/bash
        chdir: "{{ venv_path }}"
      loop: "{{ plugins }}"
