---
# Disable IPv6 

- name: Disable IPv6
  hosts: vm
  gather_facts: false
  become: true # run as root

  tasks:
    - name: Disable IPv6 with sysctl
      ansible.posix.sysctl:
        name: "{{ item }}"
        value: "1"
        state: "present"
        reload: "yes"
      with_items:
        - net.ipv6.conf.all.disable_ipv6
        - net.ipv6.conf.default.disable_ipv6
        - net.ipv6.conf.lo.disable_ipv6

    - name: Blacklist ipv6 in modprobe
      ansible.builtin.lineinfile:
        dest: /etc/modprobe.d/blacklist.conf
        line: 'blacklist ipv6'
        mode: '0644'
        create: true