---
- name: Set global variables
  hosts: localhost
  gather_facts: false
  vars: 
    work_dir: &work_dir "/opt/ansible/inventories/aruba/"

- name: Backup 'running-config' into a local folder
  hosts: aruba
  gather_facts: false
  tags: get_runs
  vars:
    work_dir: *work_dir
    ansible_connection: network_cli
  collections:
    - arubanetworks.aoscx
  tasks:
    - name: "Create group subfolder (ex: {{ group_names[1] }}) if it doesn't exits"
      file:
        path: "{{ work_dir }}/data/{{ group_names[1] }}"
        state: directory
        mode: 0775
        group: rz

    - name: Backup 'running-config' to 'group_subfolder/inventory_hostname'
      aoscx_config:
        backup: True 
        backup_options:
          filename: "{{ inventory_hostname }}"
          dir_path: "{{ work_dir }}/data/{{ group_names[1] }}"
        save_when: modified # copy to startup-config if it's different

- name: Copy config files to rhlx99 
  hosts: rhlx99
  gather_facts: false
  tags: copy_remote
  vars:
    work_dir: *work_dir
    ansible_become: true # elevate privileges on the remote machine, if necessary
    ansible_become_method: sudo
    ansible_become_pass: "{{ vault_ansible_become_pass }}"
  tasks:
    - name: Get the sub groups/folders in the "aruba" hosts group
      set_fact:
        subgroups: "{{ subgroups|default([]) | union([hostvars[item].group_names[1]]) }}"
      loop: "{{ groups.aruba }}"
      run_once: true

    - name: Copy sub folders config files to rhlx99:/tftpboot/
      copy:
        src: "{{ work_dir }}/data/{{ item }}"
        dest: "/tftpboot/"
        owner: root
        group: rz
        mode: 0666
      loop: "{{ subgroups }}"
      run_once: true
...