---
- name: Set global variables
  hosts: localhost
  gather_facts: false
  vars: 
    work_dir: &work_dir "/opt/ansible/inventories/aruba/"

- name: Generate config file for Aruba 6100 switches from Jinja template 
  hosts: new_6100
  gather_facts: false
  tags: create_config
  vars: 
    work_dir: *work_dir
  tasks:
    - name: "Create group subfolder (ex: {{ group_names[1] }}) if it doesn't exits"
      file:
        path: "{{ work_dir }}/data/{{ group_names[1] }}"
        state: directory
        mode: 0775
        group: rz

    - name: Generate file from template and save it locally
      tags: create_config
      template: 
        src: "{{ work_dir }}/playbooks/templates/new_6100.j2"
        dest: "{{ work_dir }}/data/{{ group_names[1] }}/{{ inventory_hostname }}"
        mode: 0664
        group: rz

- name: Copy generated config files to a Linux server
  hosts: rhlx99
  gather_facts: false
  tags: to_linux
  vars: 
    work_dir: *work_dir
    ansible_become: true # elevate privileges on the remote machine, if necessary
    ansible_become_method: sudo
    ansible_become_pass: "{{ vault_ansible_become_pass }}"
  tasks:
    - name: Get the sub groups/folders in the "aruba" hosts group
      set_fact:
        subgroups: "{{ subgroups|default([]) | union([hostvars[item].group_names[1]]) }}"
      loop: "{{ groups.aruba }}"
      run_once: true

    - name: Copy sub folders config files to rhlx99:/tftpboot/
      copy:
        src: "{{ work_dir }}/data/{{ item }}"
        dest: "/tftpboot/"
        owner: root
        group: rz
        mode: 0664
      loop: "{{ subgroups }}"
      run_once: true

- name: Upload configuration to switches 
  hosts: new_6100
  gather_facts: false
  tags: upload_config
  collections:
    - arubanetworks.aoscx
  vars: 
    work_dir: *work_dir
  tasks:
    - name: Upload configuration from local system file
      aoscx_config:
        src: "{{ work_dir }}/data/{{ group_names[1] }}/{{ inventory_hostname }}"
...
