- name: Reboot Aruba OS-CX switches
  hosts: "{{ target_hosts | default('aruba_aoscx') }}"
  gather_facts: false
  serial: 20
  vars:
    ansible_command_timeout: 120

  tasks:
    - name: Set formatted target firmware string
      ansible.builtin.set_fact:
        target_fw_ver: "{{ firmware_version | replace('_', '.') }}"

    - name: Get running version
      ansible.netcommon.cli_command:
        command: "show version"
      register: version_output

    - name: Get flash images status
      ansible.netcommon.cli_command:
        command: "show images"
      register: images_output

    - name: Extract Active and Primary versions
      ansible.builtin.set_fact:
        # Extracts from `show version`
        active_ver: "{{ version_output.stdout | regex_search('(?mi)^Version\\s*:\\s*(\\S+)', '\\1') | default([''], true) | first }}"
        # Extracts from `show images`
        primary_ver: "{{ images_output.stdout | regex_search('AOS-CX Primary Image[\\s\\S]*?Version\\s*:\\s*(\\S+)', '\\1') | default([''], true) | first }}"

    - name: Assert the target firmware is actually staged in Primary
      ansible.builtin.assert:
        that:
          - target_fw_ver in primary_ver
        fail_msg: "Target firmware {{ target_fw_ver }} is not in the Primary flash! Run the update playbook first."
        success_msg: "Primary flash contains the correct target firmware."
      when: target_fw_ver not in active_ver

    - name: Reboot process conditions
      when: target_fw_ver not in active_ver
      block:
        - name: Here we go!
          debug:
            msg: 
              - "{{ active_ver }}"
              - "{{ primary_ver }}"

    - name: Check for non-failsafe hardware updates
      ansible.netcommon.cli_command:
        command: "show needed-updates"
      register: updates_check

    - name: Determine the safest boot command
      ansible.builtin.set_fact:
        boot_command: >-
          {% if 'Non-failsafe device updates not enabled' in updates_check.stdout %}
          boot system primary allow-non-failsafe-updates
          {% else %}
          boot system primary
          {% endif %}
        
    - name: Show boot command
      when: "'Non-failsafe device updates not enabled' in updates_check.stdout"
      ansible.builtin.debug:
        var: boot_command