---
- name: Save 'show running-config' into a local folder
  hosts: aruba
  gather_facts: false
  collections:
    - arubanetworks.aoscx
  vars:
    ansible_connection: network_cli
  tasks:
    - name: Execute 'show running-config' on the switch and register output
      aoscx_command:
        commands: 
          - show running-config
      register: running_config

    - name: "Create group subfolder (ex: {{ group_names[1] }}) if it doesn't exits"
      when: 
        - running_config.stdout_lines[0] | length > 4 # only if it is not a single line error output
      file:
        path: "{{ group_names[1] }}"
        state: directory
        mode: 0775
      #run_once: true

    - name: Save 'running-config' to 'group_subfolder/inventory_hostname'
      when: 
        - running_config.stdout_lines[0] | length > 4 # only when it is not a single line error output
        - running_config.stdout_lines[0][0] == 'Current configuration:' # and only when output is legit
      copy:
        content: "{{ running_config.stdout[0] }}"
        dest: "{{ group_names[1] }}/{{ inventory_hostname }}"
...