---
# Show firmware version on Aruba CX switches.
#
# To run the playbook on multiple hosts simultaneously use '--forks' flag
# ansible-playbook show_version.yml --forks 50
#
- name: Show firmware version on Aruba AOS_CX 6100 switches
  hosts: aruba_6100
  gather_facts: false
  serial: 20       # Run on all hosts simultaneously
  tasks: 
      - name: Get version
        arubanetworks.aoscx.aoscx_command:
          commands: 
            - "show version"
        register: version

      - name: Show version
        ansible.builtin.debug:
          var: version.stdout_lines

- name: Show firmware version on Aruba AOS_CX 6300 switches
  hosts: aruba_6300
  gather_facts: false
  serial: 20       # Run on all hosts simultaneously
  tasks: 
      - name: Get version
        arubanetworks.aoscx.aoscx_command:
          commands: 
            - "show version"
        register: version

      - name: Show version
        ansible.builtin.debug:
          var: version.stdout_lines

- name: Show firmware version on Aruba AOS_CX 8320 switches
  hosts: aruba_8320
  gather_facts: false
  serial: 20       # Run on all hosts simultaneously
  tasks: 
      - name: Get version
        arubanetworks.aoscx.aoscx_command:
          commands: 
            - "show version"
        register: version

      - name: Show version
        ansible.builtin.debug:
          var: version.stdout_lines