---
# Show firmware version on old Aruba OS (Procurve) switches.
#
# ansible-playbook show_version_procurve.yml
#
- name: "Show firmware version on Procurve/ArubaOS switches"
  hosts: procurve
  gather_facts: false
  #serial: 20
  tasks: 
      - name: Get version
        ansible.netcommon.cli_command:
          command: "show version"
        register: version

      - name: Show version
        ansible.builtin.debug:
          var: version.stdout_lines
