---
# Show firmware version on old Aruba OS (Procurve) switches.
# ansible-playbook show_version.yaml -l procurve
#
# Show firmware version on old Aruba OS_CX 6100 switches.
# ansible-playbook show_version.yaml -l aruba_6100
- name: "Show firmware version on Procurve/ArubaOS switches"
  hosts: all
  gather_facts: false
  #serial: 20
  tasks: 
      - name: Get version
        ansible.netcommon.cli_command:
          command: "show version"
        register: version

      - name: Show version
        ansible.builtin.debug:
          var: version.stdout_lines
