---
- name: Run 'show flash' commands on ProCurve switches
  hosts: procurve
  gather_facts: false
  tasks:
    - name: get images on the switch
      ansible.netcommon.cli_command:
        command: show flash
      register: show_output

    - name: Images on switches
      debug:
        var: show_output.stdout
...
