- name: Add rules to SWITCH-ACCESS ACL (AOS-CX)
  hosts: aruba
  gather_facts: false
  collections:
    - arubanetworks.aoscx
  vars:
    ansible_connection: network_cli
  vars_files:
    - "{{ playbook_dir }}/../host_vars/aruba/vault"
  tasks:
    - name: Add ICMP, SNMP, and SNMP-TRAP rules to ACL and SNMPv3 credentials
      aoscx_command:
        commands:
          - configure terminal
          - access-list ip SWITCH-ACCESS
          - 150 permit icmp 192.168.111.196 any
          - 160 permit udp 192.168.111.196 any eq 161
          - 170 permit udp 192.168.111.196 any eq 162
          - 180 permit udp 134.108.49.9 any eq 161
          - 190 permit udp 134.108.49.9 any eq 162

    - name: Add SNMPv3 credentials
      aoscx_command:
        commands: >
          {{
            [
              'configure terminal',
              'snmpv3 security-level auth',
              'snmpv3 user checkmk auth md5 auth-pass plaintext ' ~ vault_snmp_pass,
              'snmpv3 user checkmk auth md5 auth-pass plaintext ' ~ vault_snmp_pass ~ ' access-level ro',
              'write memory'
            ]
          }}
    
- name: Debug
  hosts: localhost
  gather_facts: false
  vars_files:
    - "{{ playbook_dir }}/../host_vars/aruba/vault"
  tasks:
    - name: Sent commands
      debug:
        msg: >
          {{
            [
              'configure terminal',
              'access-list ip SWITCH-ACCESS',
              '150 permit icmp 192.168.111.196 any',
              '160 permit udp 192.168.111.196 any eq 161',
              '170 permit udp 192.168.111.196 any eq 162',
              '180 permit udp 134.108.49.9 any eq 161',
              '190 permit udp 134.108.49.9 any eq 162',
              'configure terminal',
              'snmpv3 security-level auth',
              'snmpv3 user checkmk auth md5 auth-pass plaintext ' ~ vault_snmp_pass,
              'snmpv3 user checkmk auth md5 auth-pass plaintext ' ~ vault_snmp_pass ~ ' access-level ro',
              'write memory'
            ]
          }}