---
# Update firmware on Aruba CX switches.
#
# To run the playbook specify the hosts group
# ansible-playbook update_firmware.yml -l aruba_6xxx
#
- name: Update firmware on Aruba OS-CX Switches
  hosts: aruba
  gather_facts: false
  serial: 10       # Run on 10 hosts at a time
  tasks: 
      - name: Save running configuration to startup configuration
        arubanetworks.aoscx.aoscx_command:
          commands: 
            - "write memory"

      - name: Backup current primary image to secondary partition
        arubanetworks.aoscx.aoscx_command:
          commands:
            - command: "copy primary secondary"
              prompt: "continue"
              answer: "y"
        vars: 
          ansible_command_timeout: 60

      - name: Temporarily permit TFTP traffic in the ACL
        arubanetworks.aoscx.aoscx_config:
          lines: |
            access-list ip SWITCH-ACCESS
              permit udp {{ tftp_server }} any

      - name: Download new firmware from TFTP server to primary partition
        arubanetworks.aoscx.aoscx_command:
          commands:
            - command: "{{ update_command }}"
              prompt: "[Cc]ontinue"
              answer: 
                - "y"
                - "y"
        vars: 
          ansible_command_timeout: 300
        register: tftp_output

      - name: Debug TFTP Output
        ansible.builtin.debug:
          var: tftp_output.stdout_lines
    
      - name: Remove temporary TFTP permit rule from the ACL
        arubanetworks.aoscx.aoscx_config:
          lines: |
            access-list ip SWITCH-ACCESS
              no {{ acl_line_number }}

      - name: Set boot partition to primary
        arubanetworks.aoscx.aoscx_command:
          commands:
            - "boot set-default primary"