---
# Update firmware on Aruba CX switches.
#
# To run the playbook on multiple hosts simultaneously use '--forks' flag
# ansible-playbook update_firmware.yml --forks 50
#
- name: Update firmware on Aruba 6100 switches
  hosts: aruba_6100
  gather_facts: false
  serial: 0       # Run on all hosts simultaneously
  vars: 
    work_dir: &work_dir "/opt/ansible/inventories/aruba"
    tftp_server: &tftp_server "134.108.49.9"
    firmware_version: &firmware_version "10_17_1020"
    acl_line_number: "180"
    firmware: "AOS-CX_6100-6000_{{ firmware_version }}.swi"

  tasks: 
      - name: Save running configuration to startup configuration
        arubanetworks.aoscx.aoscx_command:
          commands: 
            - "write memory"

      - name: Backup current primary image to secondary partition
        arubanetworks.aoscx.aoscx_command:
          commands:
            - command: "copy primary secondary"
              prompt: "continue"
              answer: "y"
        vars: 
          ansible_command_timeout: 60

      - name: Temporarily permit TFTP traffic in the ACL
        arubanetworks.aoscx.aoscx_config:
          lines: |
            access-list ip SWITCH-ACCESS
              permit udp {{ tftp_server }} any

      - name: Download new firmware from TFTP server to primary partition
        arubanetworks.aoscx.aoscx_command:
          commands:
            - command: "copy tftp://{{ tftp_server }}/software/{{ firmware }} primary"
              prompt: "[Cc]ontinue"
              answer: 
                - "y"
                - "y"
        vars: 
          ansible_command_timeout: 300
        register: tftp_output

      - name: Debug TFTP Output
        ansible.builtin.debug:
          var: tftp_output.stdout_lines
    
      - name: Remove temporary TFTP permit rule from the ACL
        arubanetworks.aoscx.aoscx_config:
          lines: |
            access-list ip SWITCH-ACCESS
              no {{ acl_line_number }}

      - name: Set boot partition to primary
        arubanetworks.aoscx.aoscx_command:
          commands:
            - "boot set-default primary"

      - name: Reboot the switch to apply firmware
        ansible.netcommon.cli_command:
          command: "boot system primary"
          check_all: true
          prompt:
            - "save the current configuration"
            - "[Cc]ontinue"
          answer:
            - "n"
            - "y"
        ignore_errors: true

- name: Update firmware on Aruba 6300 switches
  hosts: aruba_6300
  gather_facts: false
  vars: 
    work_dir: *work_dir
    tftp_server: *tftp_server
    firmware_version: *firmware_version
    acl_line_number: &acl_line_number "200"
    firmware: "AOS-CX_6400-6300_{{ firmware_version }}.swi"
  tasks: 
      - name: Save running configuration to startup configuration
        arubanetworks.aoscx.aoscx_command:
          commands: 
            - "write memory"

      - name: Backup current primary image to secondary partition
        arubanetworks.aoscx.aoscx_command:
          commands:
            - command: "copy primary secondary"
              prompt: "continue"
              answer: "y"
        vars: 
          ansible_command_timeout: 60

      - name: Temporarily permit TFTP traffic in the ACL
        arubanetworks.aoscx.aoscx_config:
          lines: |
            access-list ip SWITCH-ACCESS
              permit udp {{ tftp_server }} any

      - name: Download new firmware from TFTP server to primary partition
        arubanetworks.aoscx.aoscx_command:
          commands:
            - command: "copy tftp://{{ tftp_server }}/software/{{ firmware }} primary vrf mgmt"
              prompt: "[Cc]ontinue"
              answer: 
                - "y"
                - "y"
        vars: 
          ansible_command_timeout: 300
        register: tftp_output

      - name: Debug TFTP Output
        ansible.builtin.debug:
          var: tftp_output.stdout_lines
    
      - name: Remove temporary TFTP permit rule from the ACL
        arubanetworks.aoscx.aoscx_config:
          lines: |
            access-list ip SWITCH-ACCESS
              no {{ acl_line_number }}

      - name: Set boot partition to primary
        arubanetworks.aoscx.aoscx_command:
          commands:
            - "boot set-default primary"

      - name: Reboot the switch to apply firmware
        ansible.netcommon.cli_command:
          command: "boot system primary"
          check_all: true
          prompt:
            - "save the current configuration"
            - "[Cc]ontinue"
          answer:
            - "n"
            - "y"
        ignore_errors: true

- name: Update firmware on Aruba 8320 switches
  hosts: aruba_8320
  gather_facts: false
  vars: 
    work_dir: *work_dir
    tftp_server: *tftp_server
    firmware_version: *firmware_version
    acl_line_number: *acl_line_number
    firmware: "AOS-CX_8320_{{ firmware_version }}.swi"
  tasks: 
      - name: Save running configuration to startup configuration
        arubanetworks.aoscx.aoscx_command:
          commands: 
            - "write memory"

      - name: Backup current primary image to secondary partition
        arubanetworks.aoscx.aoscx_command:
          commands:
            - command: "copy primary secondary"
              prompt: "continue"
              answer: "y"
        vars: 
          ansible_command_timeout: 60

      - name: Temporarily permit TFTP traffic in the ACL
        arubanetworks.aoscx.aoscx_config:
          lines: |
            access-list ip SWITCH-ACCESS
              permit udp {{ tftp_server }} any

      - name: Download new firmware from TFTP server to primary partition
        arubanetworks.aoscx.aoscx_command:
          commands:
            - command: "copy tftp://{{ tftp_server }}/software/{{ firmware }} primary vrf mgmt"
              prompt: "[Cc]ontinue"
              answer: 
                - "y"
                - "y"
        vars: 
          ansible_command_timeout: 300
        register: tftp_output

      - name: Debug TFTP Output
        ansible.builtin.debug:
          var: tftp_output.stdout_lines
    
      - name: Remove temporary TFTP permit rule from the ACL
        arubanetworks.aoscx.aoscx_config:
          lines: |
            access-list ip SWITCH-ACCESS
              no {{ acl_line_number }}

      - name: Set boot partition to primary
        arubanetworks.aoscx.aoscx_command:
          commands:
            - "boot set-default primary"

      - name: Reboot the switch to apply firmware
        ansible.netcommon.cli_command:
          command: "boot system primary"
          check_all: true
          prompt:
            - "save the current configuration"
            - "[Cc]ontinue"
          answer:
            - "n"
            - "y"
        ignore_errors: true