---
- name: Add Aruba 6100 Switches from configuration files
  hosts: localhost
  gather_facts: false
  vars: 
    netbox_server: 192.168.122.140
    #netbox_server: netbox-bb.hs-esslingen.de
    netbox_token: "{{ vault_local_token }}"
    #netbox_token: "{{ vault_hs_netbox_token }}"
    netbox_url: "https://{{ netbox_server }}"
  tasks:
    - name: Include locations vars
      include_vars:
        file: ../data/yaml/aruba_6100.yaml

    - name: Create a Room (location)
      netbox.netbox.netbox_location:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        validate_certs: false
        data:
          name: "{{ item.name }}"
          site: "{{ item.site }}"
          parent_location: "{{ item.parent_location }}"
        state: present
      loop: "{{ locations }}"
      when: false

    - name: Add Aruba 6100-12G-POE4-2SFP+ switches
      netbox.netbox.netbox_device:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        validate_certs: false
        data:
          name: "{{ item.name }}"
          location: "{{ item.location }}"
          site: "{{ item.site }}"
          device_type: hpe-aruba-6100-12g-poe4-2sfpp
          device_role: bueroswitch
          tenant: netzadmin
        state: present
        #state: absent
      loop: "{{ aruba_6100_12g }}"
      when: false

    - name: Add found IP addresses
      netbox.netbox.netbox_ip_address:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        validate_certs: false
        data:
          address: "{{ item.address }}"
          dns_name: "{{ item.dns_name }}"
          role: "Loopback"
          tenant: netzadmin
          assigned_object:
            name: 1/1/13
            device: "{{ item.dns_name }}"
        #state: present
        state: absent
      loop: "{{ ip_addresses }}"
      #when: false

    - name: Assign IP addresses
      netbox.netbox.netbox_device:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        validate_certs: false
        data:
          name: "{{ item.name }}"
          primary_ip4: "{{ item.primary_ip4 }}"
        state: present
      loop: "{{ aruba_6100_12g }}"
      when: false

    - name: Create VLAN interfaces
      netbox.netbox.netbox_device_interface:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        validate_certs: false
        data:
          device: rggw1018bp
          name: vlan 201
          type: Virtual
          description: BB-SM
        state: present

    - name: Assign IP to VLAN interface
      netbox.netbox.netbox_ip_address:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        validate_certs: false
        data:
          address: 134.108.95.36/25
          dns_name: rggw1018bp
          description: VLAN 201 (BB-SM)
          assigned_object:
            device: rggw1018bp
            name: vlan 201
        state: present


    - name: Debugging 
      debug:
        msg: "{{ vars }}"
      when: false