---
- name: Add Aruba 6100 Switches from configuration files
  hosts: localhost
  gather_facts: false
  vars: 
    #netbox_server: 192.168.122.140
    #netbox_token: "{{ vault_local_token }}"
    netbox_server: netbox-bb.hs-esslingen.de
    netbox_token: "{{ vault_hs_netbox_token }}"
    netbox_url: "https://{{ netbox_server }}"
    done: true
  tasks:
    - name: Include locations vars
      include_vars:
        file: ../data/yaml/aruba_6100.yaml

    - name: Create a Room (location)
      netbox.netbox.netbox_location:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        validate_certs: false
        data:
          name: "{{ item.name }}"
          site: "{{ item.site }}"
          parent_location: "{{ item.parent_location }}"
        state: present
      loop: "{{ locations }}"
      when: not "{{ done }}"

    - name: Add Aruba 6100-12G-POE4-2SFP+ switches
      netbox.netbox.netbox_device:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        validate_certs: false
        data:
          name: "{{ item.name }}"
          location: "{{ item.location }}"
          site: "{{ item.site }}"
          device_type: hpe-aruba-6100-12g-poe4-2sfpp
          device_role: "{{ item.device_role }}"
          tenant: netzadmin
        state: present
        #state: absent
      loop: "{{ aruba_6100_12g }}"
      when: not "{{ done }}"

    - name: Create VLAN 1 interfaces
      netbox.netbox.netbox_device_interface:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        validate_certs: false
        data:
          device: "{{ item.name }}"
          name: "vlan 1"
          type: Virtual
        state: present
      loop: "{{ aruba_6100_12g }}"
      when: not "{{ done }}"

    - name: Create VLAN interfaces
      netbox.netbox.netbox_device_interface:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        validate_certs: false
        data:
          device: "{{ item.hostname }}"
          name: "vlan {{ item.vlan_nr }}"
          type: Virtual
          description: "{{ item.vlan_name }}"
        state: present
      loop: "{{ ip_addresses }}"
      when: not "{{ done }}"

    - name: Assign IP to VLAN interface
      netbox.netbox.netbox_ip_address:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        validate_certs: false
        data:
          address: "{{ item.ip }}"
          dns_name: "{{ item.hostname }}"
          description: "VLAN {{ item.vlan_nr }} ({{ item.vlan_name }})"
          assigned_object:
            device: "{{item.hostname }}"
            name: "vlan {{ item.vlan_nr }}"
          role: Loopback
          tenant: netzadmin
        state: present
      loop: "{{ ip_addresses }}"
      when: not "{{ done }}"

    - name: Assign IP addresses to devices
      netbox.netbox.netbox_device:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        validate_certs: false
        data:
          name: "{{ item.hostname }}"
          primary_ip4: "{{ item.ip }}"
        state: present
      loop: "{{ ip_addresses }}"
      when: not "{{ done }}"

    - name: Create LAG interfaces
      netbox.netbox.netbox_device_interface:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        validate_certs: false
        data:
          device: "{{ item.hostname }}"
          name: "lag {{ item.lag_id }}"
          type: Link Aggregation Group (LAG)
        state: present
        #state: absent
      loop: "{{ lags }}"
      when: not "{{ done }}"

    - name: Assign interfaces to LAGs
      netbox.netbox.netbox_device_interface:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        validate_certs: false
        data:
          device: "{{ item.hostname }}"
          name: "{{ item.interface }}"
          lag:
            name: "lag {{ item.lag_id}}"
        state: present
        #state: absent
      loop: "{{ lag_interfaces }}"
      when: not "{{ done }}"

    - name: Create new VLANs
      netbox.netbox.netbox_vlan:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        validate_certs: false
        data:
          name: "{{ item.name }}"
          vid: "{{ item.vlan_id }}"
        state: present
      loop: "{{ vlans }}"
      when: not "{{ done }}"

    - name: Update interfaces description
      netbox.netbox.netbox_device_interface:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        validate_certs: false
        data:
          device: "{{ item.hostname }}"
          name: "{{ item.interface }}"
          description: "{{ item.description }}"
        state: present
      loop: "{{ interfaces }}"
      when: not "{{ done }}"

    - name: Update interfaces description
      netbox.netbox.netbox_device_interface:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        validate_certs: false
        data:
          device: "{{ item.hostname }}"
          name: "{{ item.interface }}"
          mode: "{{ item.vlan_mode }}"
          untagged_vlan: "{{ item.vlan_id }}"
      loop: "{{ interfaces_vlan }}"
      when: not "{{ done }}"