# Examples production flow 
#
# ansible-playbook playbooks/aruba_6100.yaml --tags aruba_6100,development,location
# ansible-playbook playbooks/aruba_6100.yaml --tags aruba_6100,development,switches
# ansible-playbook playbooks/aruba_6100.yaml --tags aruba_6100,development,lags
# ansible-playbook playbooks/aruba_6100.yaml --tags aruba_6100,development,vlans
# ansible-playbook playbooks/aruba_6100.yaml --tags aruba_6100,development,ip
# ansible-playbook playbooks/aruba_6100.yaml --tags aruba_6100,development,interfaces
# 
# ansible-playbook playbooks/aruba_6300.yaml --tags aruba_6300,production,location
# ansible-playbook playbooks/aruba_6300.yaml --tags aruba_6300,production,switches
# ansible-playbook playbooks/aruba_6300.yaml --tags aruba_6300,production,lags
# ansible-playbook playbooks/aruba_6300.yaml --tags aruba_6300,production,vlans
# ansible-playbook playbooks/aruba_6300.yaml --tags aruba_6300,production,ip
# ansible-playbook playbooks/aruba_6300.yaml --tags aruba_6300,production,interfaces

---
- name: Add Aruba 6100 Switches from configuration files
  hosts: localhost
  gather_facts: false
  vars: 
    netbox_url: "https://{{ netbox_server }}"
  tasks:
    - name: Include locations vars vor Aruba 6100 switches
      tags: aruba_6100
      include_vars:
        file: ../data/yaml/aruba_6100.yaml

    - name: Include locations vars vor Aruba 6300 switches
      tags: aruba_6300
      include_vars:
        file: ../data/yaml/aruba_6300.yaml

    - name: Include test vars
      tags: test
      include_vars:
        file: ../data/yaml/test.yaml

    - name: Include development server variables
      tags: development
      include_vars:
        file: ../data/src/development_server.yaml

    - name: Include production server variables
      tags: production
      include_vars:
        file: ../data/src/production_server.yaml

    - name: Create a Room (location)
      tags: 
        - location
        - add_switches
        - switches
      netbox.netbox.netbox_location:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        validate_certs: false
        data:
          name: "{{ item.name }}"
          site: "{{ item.site }}"
          parent_location: "{{ item.parent_location }}"
        state: present
      loop: "{{ locations }}"

    - name: Add switches
      tags: 
        - switches
        - add_switches
      netbox.netbox.netbox_device:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        validate_certs: false
        data:
          name: "{{ item.name }}"
          location: "{{ item.location }}"
          site: "{{ item.site }}"
          device_type: "{{ item.device_type }}"
          device_role: "{{ item.device_role }}"
          serial: "{{ item.serial }}"
          tags: "{{ item.tags }}"
          tenant: netzadmin
        state: present
      loop: "{{ devices }}"

    - name: Create VLAN 1 interfaces
      tags: 
        - vlan_1
        - create_vlans
        - vlans
      netbox.netbox.netbox_device_interface:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        validate_certs: false
        data:
          device: "{{ item.name }}"
          name: "vlan 1"
          type: Virtual
        state: present
      loop: "{{ devices }}"

    - name: Create VLAN interfaces
      tags: 
        - create_vlan_interfaces
        - vlans
      netbox.netbox.netbox_device_interface:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        validate_certs: false
        data:
          device: "{{ item.hostname }}"
          name: "vlan {{ item.vlan_nr }}"
          type: Virtual
          description: "{{ item.vlan_name }}"
        state: present
      loop: "{{ ip_addresses }}"

    - name: Assign IP to VLAN interface
      tags:
        - ip_to_vlans
        - ip
      netbox.netbox.netbox_ip_address:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        validate_certs: false
        data:
          address: "{{ item.ip }}"
          dns_name: "{{ item.hostname }}"
          description: "VLAN {{ item.vlan_nr }} ({{ item.vlan_name }})"
          assigned_object:
            device: "{{item.hostname }}"
            name: "vlan {{ item.vlan_nr }}"
          role: Loopback
          tenant: netzadmin
        state: present
      loop: "{{ ip_addresses }}"

    - name: Assign IP addresses to devices
      tags:
        - ip_to_devices
        - ip
      netbox.netbox.netbox_device:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        validate_certs: false
        data:
          name: "{{ item.hostname }}"
          primary_ip4: "{{ item.ip }}"
        state: present
      loop: "{{ ip_addresses }}"

    - name: Create LAG interfaces
      tags:
        - create_lags
        - lags
      netbox.netbox.netbox_device_interface:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        validate_certs: false
        data:
          device: "{{ item.hostname }}"
          name: "lag {{ item.lag_id }}"
          type: Link Aggregation Group (LAG)
        state: present
      loop: "{{ lags }}"

    - name: Assign interfaces to LAGs
      tags:
        - ip_to_lags
        - ip
      netbox.netbox.netbox_device_interface:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        validate_certs: false
        data:
          device: "{{ item.hostname }}"
          name: "{{ item.interface }}"
          lag:
            name: "lag {{ item.lag_id}}"
        state: present
      loop: "{{ lag_interfaces }}"

    - name: Create new VLANs
      tags: 
        - create_vlans
        - vlans
      netbox.netbox.netbox_vlan:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        validate_certs: false
        data:
          name: "{{ item.name }}"
          vid: "{{ item.vlan_id }}"
        state: present
      loop: "{{ vlans }}"

    - name: Update interfaces description
      tags:
        - interface_description
        - interfaces
      netbox.netbox.netbox_device_interface:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        validate_certs: false
        data:
          device: "{{ item.hostname }}"
          name: "{{ item.interface }}"
          description: "{{ item.description }}"
        state: present
      loop: "{{ interfaces }}"

    - name: Assign untagged vlans to interfaces
      tags:
        - vlans_to_interfaces
        - interfaces
      netbox.netbox.netbox_device_interface:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        validate_certs: false
        data:
          device: "{{ item.hostname }}"
          name: "{{ item.interface }}"
          mode: "{{ item.vlan_mode }}"
          untagged_vlan: 
            vlan_id: "{{ item.vlan_id }}"
            name: "{{ item.vlan_name }}"
      loop: "{{ interfaces_vlan }}"