---
- name: Test device module
  hosts: localhost
  gather_facts: false
  vars: 
    netbox_server: 192.168.122.140
    #netbox_server: netbox-bb.hs-esslingen.de
    netbox_token: "{{ vault_local_token }}"
    #netbox_token: "{{ vault_hs_netbox_token }}"
    netbox_url: "https://{{ netbox_server }}"
  tasks:
    - name: Include locations vars
      include_vars:
        file: ../data/yaml/aruba_6100.yaml

    - name: Create a Room (location)
      netbox.netbox.netbox_location:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        validate_certs: false
        data:
          name: "{{ item.name }}"
          site: "{{ item.site }}"
          parent_location: "{{ item.parent_location }}"
        state: present
      loop: "{{ locations }}"
      when: false

    - name: Add Aruba 6100-12G-POE4-2SFP+ switches
      netbox.netbox.netbox_device:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        validate_certs: false
        data:
          name: "{{ item.name }}"
          location: "{{ item.location }}"
          site: "{{ item.site }}"
          primary_ip4: "{{ item.primary_ip4 }}"
          device_type: hpe-aruba-6100-12g-poe4-2sfpp
          device_role: bueroswitch
          tenant: netzadmin
        state: present
      loop: "{{ aruba_6100_12g }}"
      when: false

    - name: Debugging 
      debug:
        msg: "{{ vars }}"
      when: false