---
- name: Test device module
  hosts: localhost
  gather_facts: false
  vars: 
    #netbox_server: 192.168.122.140
    netbox_server: netbox-bb.hs-esslingen.de
    netbox_url: "https://{{ netbox_server }}"
    #netbox_token: "{{ vault_local_token }}"
    netbox_token: "{{ vault_hs_netbox_token }}"
  tasks:
    - name: Include locations vars
      include_vars:
        file: ../data/yaml/locations.yaml

    - name: Create a Room (location)
      netbox.netbox.netbox_location:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        validate_certs: false
        data:
          name: "{{ item.name }}"
          site: "{{ item.site }}"
          parent_location: "{{ item.parent_location }}"
        state: present
      loop: "{{ locations }}"

    - name: Add Aruba 6100 Switch
      netbox.netbox.netbox_device:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        validate_certs: false
        data:
          name: rhgw1035p
          device_type: hpe-aruba-6100-12g-poe4-2sfpp
          device_role: bueroswitch
          tenant: netzadmin
          location: f01-0-erdgeschoss
          site: campus-flandernstrasse
        state: present
      when: false

    - name: Debugging 
      debug:
        msg: "{{ vars }}"
      when: false