---
- name: Add ProCurve Single Switches from configuration files
  hosts: localhost
  gather_facts: false
  vars: 
    netbox_url: "https://{{ netbox_server }}"
  tasks:
    - name: Include data file 
      tags: data
      include_vars:
        file: ../data/yaml/hp_single.yaml

    - name: Include development server variables
      tags: development
      include_vars:
        file: ../data/src/development_server.yaml

    - name: Include production server variables
      tags: production
      include_vars:
        file: ../data/src/production_server.yaml

    - name: Add switches
      tags: switches
      netbox.netbox.netbox_device:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        validate_certs: false
        data:
          name: "{{ item.name }}"
          site: "{{ item.site }}"
          device_type: "{{ item.device_type }}" 
          device_role: "{{ item.device_role }}"
          serial: "{{ item.serial }}"
          tags: "{{ item.tags }}"
          tenant: netzadmin
        state: present
        #state: absent
      loop: "{{ devices }}"

    - name: Create Trunk interfaces as LAG
      tags: 
        - lags
        - trunks
      netbox.netbox.netbox_device_interface:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        validate_certs: false
        data:
          device: "{{ item.hostname }}"
          name: "{{ item.name }}"
          type: Link Aggregation Group (LAG)
        state: present
        #state: absent
      loop: "{{ trunks }}"

    - name: Assign interfaces to Trunks
      tags: 
        - trunk_interfaces
        - trunks
      netbox.netbox.netbox_device_interface:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        validate_certs: false
        data:
          device: "{{ item.hostname }}"
          name: "{{ item.interface }}"
          lag:
            name: "{{ item.trunk_name }}"
        state: present
        #state: absent
      loop: "{{ trunk_interfaces }}"

    - name: Update interfaces description (here name)
      tags: 
        - interfaces
      netbox.netbox.netbox_device_interface:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        validate_certs: false
        data:
          device: "{{ item.hostname }}"
          name: "{{ item.interface }}"
          description: "{{ item.name }}"
        state: present
      loop: "{{ interface_names }}"

    - name: Create VLANs
      tags: 
        - create_vlans
        - vlans
      netbox.netbox.netbox_vlan:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        validate_certs: false
        data:
          name: "{{ item.name }}"
          vid: "{{ item.id }}"
        state: present
      loop: "{{ vlans }}"
    