---
- name: Add ProCurve 5406zl Switches from configuration files
  hosts: localhost
  gather_facts: false
  vars: 
    netbox_server: 192.168.122.140
    netbox_token: "{{ vault_local_token }}"
    #netbox_server: netbox-bb.hs-esslingen.de
    #netbox_token: "{{ vault_hs_netbox_token }}"
    netbox_url: "https://{{ netbox_server }}"
    #do_it: yes
    do_it: no
  tasks:
    - name: Include locations vars
      include_vars:
        file: ../data/yaml/j8697a.yaml

    - name: Add switches
      netbox.netbox.netbox_device:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        validate_certs: false
        data:
          name: "{{ item.name }}"
          site: "{{ item.site }}"
          device_type: hpe-procurve-5406zl
          device_role: "{{ item.device_role }}"
          tags: "{{ item.tags }}"
          tenant: netzadmin
        state: present
        #state: absent
      loop: "{{ devices }}"
      when: "{{ do_it }}"

    - name: Delete module bays
      netbox.netbox.netbox_module_bay:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        validate_certs: false
        data:
          device: "{{ item.device }}"
          name: "{{ item.module_bay }}"
          position: "{{ item.module_bay }}"
        state: absent
      loop: "{{ modules }}"
      when: "{{ do_it }}"

    - name: Create module bays
      netbox.netbox.netbox_module_bay:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        validate_certs: false
        data:
          device: "{{ item.device }}"
          name: "{{ item.device }}-{{ item.module_bay }}"
          position: "{{ item.module_bay }}"
        state: present
      loop: "{{ modules }}"
      when: "{{ do_it }}"

    - name: Add modules
      netbox.netbox.netbox_module:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        validate_certs: false
        data:
          device: "{{ item.device }}"
          module_bay: "{{ item.device }}-{{ item.module_bay }}"
          module_type: "{{ item.type }}"
          status: active
        state: present
      loop: "{{ modules }}"
      when: "{{ do_it }}"

    - name: Create Trunk interfaces as LAG
      netbox.netbox.netbox_device_interface:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        validate_certs: false
        data:
          device: "{{ item.hostname }}"
          name: "{{ item.name }}"
          type: Link Aggregation Group (LAG)
        state: present
        #state: absent
      loop: "{{ trunks }}"
      when: "{{ do_it }}"

    - name: Assign interfaces to Trunks
      netbox.netbox.netbox_device_interface:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        validate_certs: false
        data:
          device: "{{ item.hostname }}"
          name: "{{ item.interface }}"
          lag:
            name: "{{ item.trunk_name }}"
        state: present
        #state: absent
      loop: "{{ trunk_interfaces }}"
      when: "{{ do_it }}"

    - name: Update interfaces description (here name)
      netbox.netbox.netbox_device_interface:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        validate_certs: false
        data:
          device: "{{ item.hostname }}"
          name: "{{ item.interface }}"
          description: "{{ item.name }}"
        state: present
      loop: "{{ interface_names }}"
      when: "{{ do_it }}"

    - name: Create VLANs
      netbox.netbox.netbox_vlan:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        validate_certs: false
        data:
          name: "{{ item.name }}"
          vid: "{{ item.id }}"
        state: present
      loop: "{{ vlans }}"
      when: "{{ do_it }}"
