---
plugins:
  - netbox-bgp
  - netbox-documents
  - netbox-floorplan-plugin
  - netbox_acls
  - netbox-plugin-dns
  - netbox-qrcode
  - netbox-reorder-rack
  - netbox-topology-views
  - netbox-inventory
