---
# CIS Benchmark 1.1.2. - Configure Filesystem Partitions
# Checks that specific directories are on separate partitions ot `tmpfs`, 
# with required mount options.
# Rationale: Prevents unauthorized device access, SUID execution, and code execution
# on directories that should not contain user executables.
#
# Directories with separate partitions or is tmpfs:
#   /tmp, /dev/shm 
#
# Directories with separate partitions:
#   /home, /var, /var/tmp, /var/log, /var/log/audit
#
# Directories with nodev, nosuid, noexec:
#   /tmp, /dev/shm, /var/tmp, /var/log, 
#   and /var/log/audit - for auditd deamon, which is usually missing
#
# Directories with nodev, nosuid (no noexec):
#   /home, /var
#
# Note: If /tmp entry exists in /etc/fstab, it takes precedence over systemd unit file.
#       On diskless/iSCSI systems, fstab may not override systemd configuration.
#
# Audit:
#   1. findmnt -kn [DIR] # DIR example: /tmp
#     Example output: /tmp tmpfs tmpfs rw,nosuid,nodev,noexec
#   2.  findmnt -kn [DIR] | grep -v [OPT] # OPT example: noexec
#     Nothing should be returned
#
# Remediation 1: (example for /tmp)
#   systemctl unmask tmp.mount
#   Edit /etc/fstab: tmpfs /tmp tmpfs defaults,rw,nosuid,nodev,noexec,relatime,size=2G 0 0
# Remediation 2: (example for /tmp and noexec) 
#   - IF - a separate partition exists for /tmp.
#   Edit the /etc/fstab file and add noexec to the fourth field (mounting options) for the 
#   /tmp partition.
#     Example:
#     <device> /tmp  <fstype>  defaults,rw,nosuid,nodev,noexec,relatime  0 0
#   Run the following command to remount /tmp with the configured options:
#   mount -o remount /tmp

- name: Check partitions mount configuration per CIS
  hosts: local
  become: true
  gather_facts: false

  vars:
    partitions_tmpfs:
      - '/tmp'
      - '/dev/shm'
    partitions:
      - '/home'
      - '/var'
      - '/var/tmp'
      - '/var/log'
      #- '/var/log/audit'
    noexec_partiotions:
      - '/tmp'
      - '/dev/shm'
      - '/var/tmp'
      - '/var/log'
      #- '/var/log/audit'

    root_filesystems: "rootfs,unknown"
    valid_systemd_statuses: "enabled,generated,static"

  tasks:
    # Step 1: Check if partitions are mounted
    - name: Get existing tmpfs partitions mount data
      ansible.builtin.shell: "findmnt -kn {{ item }} | grep tmpfs"
      register: tmpfs_parts
      changed_when: false
      failed_when: false
      loop: "{{ partitions_tmpfs }}"

    - name: Get existing partitions mount data
      ansible.builtin.shell: "findmnt -kn {{ item }}"
      register: default_parts
      changed_when: false
      failed_when: false
      loop: "{{ partitions }}"

    - name: Set fact for tmpfs mounted partitions
      ansible.builtin.set_fact:
        mounted_tmpfs_partitions: >-
          {{
            tmpfs_parts.results
            | map(attribute='stdout_lines')
            | flatten
            | select('match', '.+')
            | list
          }}

    - name: Set fact for default mounted partitions
      ansible.builtin.set_fact:
        mounted_partitions: >-
          {{
            default_parts.results
            | map(attribute='stdout_lines')
            | flatten
            | select('match', '.+')
            | list
          }}

    - name: Mounted tmpfs partitions found
      ansible.builtin.debug:
        msg: "{{ mounted_tmpfs_partitions }}"

    - name: Mounted default partitions found
      ansible.builtin.debug:
        msg: "{{ mounted_partitions }}"

    - name: Extract tmpfs mount points into tmpfs_mount_points
      ansible.builtin.set_fact:
        tmpfs_mount_points: >-
          {{
            mounted_tmpfs_partitions
            | map('split', ' ')
            | map('first')
            | list
          }}

    - name: Extract default mount points into default_mount_points
      ansible.builtin.set_fact:
        default_mount_points: >-
          {{
            mounted_partitions
            | map('split', ' ')
            | map('first')
            | list
          }}

    - name: Assert all tmpfs required partitions are mounted
      ansible.builtin.assert:
        that: item in tmpfs_mount_points
        fail_msg: |
          {{ item }} isn't mounted or doesn't exist!

          You have to create a new partition and configure /etc/fstab accordingly. For Example:

          tmpfs {{ item }}     tmpfs    defaults,rw,nosuid,nodev,noexec,relatime,size=2G 0 0

          Note: the size=2G is an example of setting a specific size for tmpfs.
          Example of using a volume or disk with specific mount options. The source location of
          the volume or disk will vary depending on your environment:

          <device> {{ item }}    <fstype>   defaults,nodev,nosuid   0 0
        success_msg: "{{ item }} partition is correctly mounted as tmpfs"
      loop: "{{ partitions_tmpfs }}"

    - name: Assert all required partitions are mounted
      ansible.builtin.assert:
        that: item in default_mount_points
        fail_msg: |
          WARNING: {{ item }} isn't mounted or doesn't exist!

          If {{ item }} already exists, create a new partition, mount the new partition to a temporary mountpoint e.g. 
          
          mount /dev/vdb2 /mnt

          Copy data from the original partition to the new partition. e.g. 
          
          rsync -avz {{ item }}/* /mnt 
          
          Verify that all data is present on the new partition. e.g. 
          
          ls -la /mnt
          
          Unmount the new partition. e.g. 
          
          umount /mnt

          Remove the data from the original directory that was in the old partition. e.g. 
          
          rm -Rf {{ item }}/* 
          
          Otherwise it will still consume space in the old partition that will be masked when the new filesystem is mounted.

          Mount the new partition to the desired mountpoint. e.g. 
          
          mount /dev/vdb2 {{ item }}

          Update /etc/fstab with the new mountpoint. e.g. 
          
          <partition UUID> {{ item }} <partition TYPE> defaults,rw,nosuid,nodev,noexec,relatime 0 0

          To get partition UUID and type: 

          blkid
        success_msg: "{{ item }} partition exists, is correctly mounted and configured"
      loop: "{{ partitions }}"

    # Step 2 Ensure filesystem options are correctly set 
    - name: Collect filesystems mount data
      ansible.builtin.shell: "findmnt -kn {{ item }}"
      register: raw_mount_data
      changed_when: false
      failed_when: false
      loop: "{{ partitions_tmpfs + partitions }}"

    - name: Set fact for mount data
      ansible.builtin.set_fact:
        mount_data: >-
          {{
            raw_mount_data.results
            | map(attribute='stdout')
            | flatten
            | select('match', '.+')
            | list
          }}

    - name: Collected mount data
      ansible.builtin.debug:
        msg: "{{ mount_data }}"

    - name: Initialize list for missing nosuid
      ansible.builtin.set_fact:
        missing_nosuid: []

    - name: Check for nosuid in each mount line
      ansible.builtin.set_fact:
        missing_nosuid: "{{ missing_nosuid + [item.split(' ')[0]] }}"
      loop: "{{ mount_data }}"
      when: "'nosuid' not in item.split(' ')[3]"

    - name: Debug missing nosuid
      ansible.builtin.debug:
        msg: "Mount points missing nosuid: {{ missing_nosuid }}"

    - name: Assert nosuid option missing
      ansible.builtin.assert:
        that: item not in missing_nosuid
        fail_msg: |
          ERROR: Missing nosuid option for partition {{ item }}

          Edit the /etc/fstab file and add nosuid to the fourth field (mounting options) for the {{ item }} partition.

          Example:
          <device> {{ item }} <fstype> defaults,rw,nosuid,relatime 0 0
          
          Run the following command to remount /var/log/audit with the configured options:

          mount -o remount {{ item }}
        success_msg: "{{ item }} partition exists with nosuid option."
      loop: "{{ partitions + partitions_tmpfs }}"

    - name: Initialize list for missing nodev
      ansible.builtin.set_fact:
        missing_nodev: []

    - name: Check for nodev in each mount line
      ansible.builtin.set_fact:
        missing_nodev: "{{ missing_nodev + [item.split(' ')[0]] }}"
      loop: "{{ mount_data }}"
      when: "'nodev' not in item.split(' ')[3]"

    - name: Debug missing nodev
      ansible.builtin.debug:
        msg: "Mount points missing nodev: {{ missing_nodev }}"

    - name: Assert nodev option missing
      ansible.builtin.assert:
        that: item not in missing_nodev
        fail_msg: |
          ERROR: Missing nodev option for partition {{ item }}

          Edit the /etc/fstab file and add nodev to the fourth field (mounting options) for the {{ item }} partition.

          Example:
          <device> {{ item }} <fstype> defaults,rw,nosuid,nodev,relatime 0 0
          
          Run the following command to remount /var/log/audit with the configured options:

          mount -o remount {{ item }}
        success_msg: "{{ item }} partition exists with nodev option."
      loop: "{{ partitions + partitions_tmpfs }}"

    - name: Collect filesystems mount data for noexec partitions
      ansible.builtin.shell: "findmnt -kn {{ item }}"
      register: raw_noexec_mount_data
      changed_when: false
      failed_when: false
      loop: "{{ noexec_partiotions }}"

    - name: Set fact for noexec partitions mount data
      ansible.builtin.set_fact:
        noexec_mount_data: >-
          {{
            raw_noexec_mount_data.results
            | map(attribute='stdout')
            | flatten
            | select('match', '.+')
            | list
          }}

    - name: Initialize list for missing noexec
      ansible.builtin.set_fact:
        missing_noexec: []

    - name: Check for noexec in each mount line
      ansible.builtin.set_fact:
        missing_noexec: "{{ missing_noexec + [item.split(' ')[0]] }}"
      loop: "{{ noexec_mount_data }}"
      when: "'noexec' not in item.split(' ')[3]"

    - name: Debug missing noexec
      ansible.builtin.debug:
        msg: "Mount points missing noexec: {{ missing_noexec | join(', ') }}"

    - name: Assert noexec option missing
      ansible.builtin.assert:
        that: item not in missing_noexec
        fail_msg: |
          ERROR: Missing noexec option for partition {{ item }}

          Edit the /etc/fstab file and add noexec to the fourth field (mounting options) for the {{ item }} partition.

          Example:
          <device> {{ item }} <fstype> defaults,rw,nosuid,nodev,noexec,relatime 0 0
          
          Run the following command to remount /var/log/audit with the configured options:

          mount -o remount {{ item }}
        success_msg: "{{ item }} partition exists with noexec option."
      loop: "{{ noexec_partiotions }}"