---
# Rocky Linux server full system update & cleanup
#
# RUN:
# ansible-playbook playbooks/dnf_install.yaml -l <hosts>

- name: System update and cleanup
  hosts: hs_23
  gather_facts: false
  tags: update
  become: true
  tasks:
    - name: Update all packages
      ansible.builtin.dnf:
        name: "*"
        state: latest
        update_cache: true

    - name: Install packages and dependencies
      ansible.builtin.dnf: 
        pkg: "{{ item }}"
        state: latest
        update_cache: true
      loop:
        - vim
        - epel-release
        - ufw
        - postfix
        - chrony
        - rsyslog
        - rpcbind
        - avahi
        - tftp-server
        - at
        - screen
        - dnf-automatic 
        - plocate
        - munin-node
        - nrpe
    
    - name: Remove unnecessary packages
      ansible.builtin.dnf:
        autoremove: true

    - name: Get running kernel version
      ansible.builtin.command: "uname -r"
      register: running_kernel
      changed_when: false

    - name: Get latest installed kernel version
      ansible.builtin.shell: "rpm -qa kernel"
      register: installed_kernel
      changed_when: false

    - name: Show kernels
      debug:
        msg: 
          - "Running Kernel: kernel-{{ running_kernel.stdout }}" 
          - "Installed Kernel: {{ installed_kernel.stdout_lines }}"

    - name: Reboot if a new kernel is installed
      ansible.builtin.reboot:
      when: "'kernel-' + running_kernel.stdout not in installed_kernel.stdout_lines"
...