---
- name: Install and configure initial firewall
  hosts: all
  gather_facts: false
  become: true # run as root
  vars:
    ip_list_admin: 
      - 134.108.0.0/24
      - 134.108.64.0/24
      - 134.108.96.0/24
      - 134.108.62.196/27
      - 134.108.52.0/25
      - 134.108.49.1 # rhlx0023
    ip_list_netz: 
      - 134.108.62.196
      - 134.108.62.197
      - 134.108.62.217
      - 134.108.62.219
      - 134.108.49.1 # rhlx0023
    ip_list_services:
      - 134.108.34.114
      - 134.108.34.214
  tasks: 
    - name: Install ufw package
      apt: 
        pkg: ufw
        state: latest
        update_cache: true

    - name: Deny all incoming connections
      community.general.ufw:
        default: deny
        direction: incoming

    - name: Allow all outgoing traffic
      community.general.ufw:
        default: allow
        direction: outgoing

    - name: Allow Nagios
      community.general.ufw:
        rule: allow
        port: 4949
        src: "{{ item }}"
      loop: "{{ ip_list_services }}"

    - name: Allow munin 
      community.general.ufw:
        rule: allow
        port: 5666
        src: "{{ item }}"
      loop: "{{ ip_list_services }}"

    - name: Allow SSH connections on port 22 for net admins
      community.general.ufw:
        rule: allow
        port: ssh
        src: "{{ item }}"
      loop: "{{ ip_list_netz }}"

    - name: Delete general SSH connections, if any
      community.general.ufw:
        rule: allow
        port: "{{ item }}"
        delete: true
      loop:
        - ssh
        - 22
      
    - name: Delete general OpenSSH policy, if any
      community.general.ufw:
        rule: allow
        name: OpenSSH
        delete: true

    - name: Allow HTTP connections for net admins
      community.general.ufw:
        rule: allow
        port: http
        src: "{{ item }}"
      loop: "{{ ip_list_netz }}"

    - name: Allow HTTPS connections for HE admins
      community.general.ufw:
        rule: allow
        port: https
        src: "{{ item }}"
      loop: "{{ ip_list_admin }}"

    - name: Delete general HTTP and HTTPS connections, if any
      community.general.ufw:
        rule: allow
        port: "{{ item }}"
        delete: true
      loop:
        - http
        - https
        - 80
        - 443
    
    - name: Enable ufw firewall if it's disabled
      community.general.ufw:
        state: enabled
