---
# Copy Cisco firmware overs SSH
#
# To run the playbook:
# ansible-playbook clean_firmware.yml
#
- name: "Clean devices firmware"
  hosts: cisco
  gather_facts: false
  #serial: 5

  tasks: 
      # ---------------------------------------------------------
      # MAIN FILESYSTEM CLEANUP BLOCK
      # ---------------------------------------------------------
      - name: Clean main filesystem
        block:
          - name: Verify New Firmware Version is Active
            ansible.netcommon.cli_command:
              command: "show version"
            register: sh_version

          - name: Assert VSS cluster upgraded successfully
            ansible.builtin.assert:
              that:
                - "firmware_version in sh_version.stdout"
              fail_msg: "CRITICAL: Switch booted back into the old firmware!"

          - name: Verify Standby Supervisor has fully joined the VSS cluster for 4506-E
            ansible.netcommon.cli_command:
              command: "show redundancy"
            register: redundancy_status
            # Wait up to 10 minutes for the Standby to fully boot and sync
            until: "'STANDBY HOT' in redundancy_status.stdout"
            retries: 10
            delay: 60
            when: inventory_hostname in groups['catalyst_4506es']

          # ---------------------------------------------------------
          # 4506-E CLEANUP BLOCK
          # ---------------------------------------------------------
          - name: CLEANUP 4506-E - Remove previous firmware 
            block:
              - name: CLEANUP - Remove previous firmware from Active Supervisor
                ansible.netcommon.cli_command:
                  command: "delete /force {{ filesystem }}:{{ previous_firmware }}"
                ignore_errors: true

              - name: CLEANUP - Remove previous firmware from 4506-E Standby Supervisor
                ansible.netcommon.cli_command:
                  command: "delete /force slavebootflash:{{ previous_firmware }}"
                ignore_errors: true
            when: 
              - inventory_hostname in groups['catalyst_4506es']
              - "'STANDBY HOT' in redundancy_status.stdout"

          # ---------------------------------------------------------
          # 2960-X CLEANUP BLOCK
          # ---------------------------------------------------------
          - name: CLEANUP 2960-X - Remove previous firmware 
            block:
              - name: Verify all the stacks have fully joined the VSS cluster for 2960-X
                ansible.builtin.assert:
                  that:
                    - "previous_firmware_version not in sh_version.stdout"
                  fail_msg: "CRITICAL: Stacks booted back into the old firmware!"

              - name: CLEANUP - Remove previous firmware from 2960-X main flash 
                ansible.netcommon.cli_command:
                  command: "delete /force {{ filesystem }}:{{ previous_firmware }}"
                ignore_errors: true

              - name: CLEANUP - Remove previous firmware from 2960-X Stack Members
                ansible.netcommon.cli_command:
                  command: "delete /force flash{{ item }}:{{ previous_firmware }}"
                ignore_errors: true
                loop: "{{ range(1, (stack_size | int) + 1) }}"
            when: inventory_hostname in groups['catalyst_2960x']
