---
- name: Debugging
  hosts: cisco
  gather_facts: false
  #serial: 1
  tasks:

#    - name: Show hosts variables
#      ansible.builtin.debug:
#        var: "{{ hostvars[inventory_hostname] }}"

    - name: Get version
      ansible.netcommon.cli_command:
        command: "show version"
      register: version

    - name: Show version
      ansible.builtin.debug:
        var: version.stdout_lines
      
    - name: Show firmware to be installed
      ansible.builtin.debug:
        var: firmware

    - name: Execute 9500 ISSU Commands
      block:
        - name: Show upgrade command
          ansible.builtin.debug:
            msg: "install add file {{ filesystem }}:{{ firmware }} activate issu commit"
      when: 
        - inventory_hostname in groups['catalyst_9500']
        # Only run this block if the switch is in Install Mode
        - "'packages.conf' in version.stdout"

    - name: Execute 9500 Upgrade and Convert to Install Mode
      block:
        - name: Show upgrade and convert command
          ansible.builtin.debug:
            msg: "install add file {{ filesystem }}:{{ firmware }} activate commit"
      when: 
        - inventory_hostname in groups['catalyst_9500']
        # Only run this block if the switch is in Install Mode
        - "'packages.conf' not in version.stdout"

    - name: Check if firmware exists on 2960-X Stack Members
      block:
        - name: Collect the stacks with available firmware
          ansible.netcommon.cli_command:
            # Loops through flash2:, flash3:, etc.
            command: "dir flash{{ item }}:{{ firmware }}"
          register: file_check_2960_slaves
          ignore_errors: true
          loop: "{{ range(2, (stack_size | int) + 1) }}"

        - name: Show collected stacks
          debug:
            msg: "{{ file_check_2960_slaves }}"
      when: inventory_hostname in groups['catalyst_2960x']

    - name: Verify new firmware on 4506-E slave filesystems
      block:
        - name: Verify firmware digital signature on Active Supervisor
          ansible.netcommon.cli_command:
            command: "verify {{ filesystem }}:{{ firmware }}"
          vars:
            ansible_command_timeout: 300
          register: verify_active

        - name: Assert Active firmware is not corrupted (PKI)
          ansible.builtin.assert:
            that:
              - "'Digital signature successfully verified' in verify_active.stdout"
            fail_msg: "CRITICAL: Firmware on bootflash is corrupt. Do not copy to standby!"

        - name: Generate MD5 hash for Active firmware
          ansible.netcommon.cli_command:
            command: "verify /md5 {{ filesystem }}:{{ firmware }}"
          vars:
            ansible_command_timeout: 1800
          register: md5_active

        - name: Extract MD5 hash string from Active supervisor
          ansible.builtin.set_fact:
            # Scans the output and isolates the 32-character hex string
            active_hash: "{{ md5_active.stdout | regex_search('([a-fA-F0-9]{32})') }}"

        - name: Display the MD5 hash 
          debug:
            msg: "{{ active_hash }}"

        - name: Check if valid firmware exists on Standby (Native IOS Compare)
          ansible.netcommon.cli_command:
            # Passes the extracted hash directly to the switch for comparison
            command: "verify /md5 slavebootflash:{{ firmware }} {{ active_hash }}"
          vars:
            ansible_command_timeout: 1800
          register: initial_md5_standby
          ignore_errors: true

      when: inventory_hostname in groups['catalyst_4506es']